eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.117:3306/PGMaster?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: pg
    password: sharepoint@admin

# tomcat   
    tomcat:
      max-active: 0
      max-idle: 0

# service name
  application:
    name: ms-provider-user-store

# exception handle
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  
# server
server:
  port: 8762

# mybatis
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

